"use client";
import { useEffect, useState } from "react";import { useRouter } from "next/navigation";import ReactMarkdown from "react-markdown";import remarkGfm from "remark-gfm";import { Bot,Columns2,Eye,History,Save,Undo2 } from "lucide-react";import type { Artifact,Project } from "@/lib/types";import { analyzeImpact,calculateHealth } from "@/lib/intelligence";import type { VersionDto } from "@/lib/project-repository";

async function jsonOrError(response:Response){const text=await response.text();let body:Record<string,unknown>={};try{body=text?JSON.parse(text):{};}catch{throw new Error(`Server returned ${response.status}`);}if(!response.ok)throw new Error(String(body.error??`Request failed (${response.status})`));return body;}

export function ArtifactWorkspace({project,initial,initialVersions,canEdit}:{project:Project;initial:Artifact;initialVersions:VersionDto[];canEdit:boolean}){
 const router=useRouter();const[content,setContent]=useState(initial.content),[mode,setMode]=useState<"edit"|"preview"|"split">("edit"),[versions,setVersions]=useState(initialVersions),[busy,setBusy]=useState<"save"|"restore"|"ai"|null>(null),[prompt,setPrompt]=useState(""),[answer,setAnswer]=useState(""),[error,setError]=useState(""),[dirty,setDirty]=useState(false);useEffect(()=>{if(!dirty)return;const handler=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[dirty]);const currentVersion=versions.find(v=>v.current)?.version??initial.version,impact=analyzeImpact(project,initial.id),health=calculateHealth(project);
 async function save(){setBusy("save");setError("");try{const response=await fetch("/api/artifacts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({projectKey:project.id,artifactKey:initial.id,content,reason:"Workspace edit",expectedVersion:currentVersion})});const body=await jsonOrError(response);setVersions(body.versions as VersionDto[]);setDirty(false);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Save failed");}finally{setBusy(null);}}
 async function restore(version:number){setBusy("restore");setError("");try{const response=await fetch("/api/artifacts/restore",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectKey:project.id,artifactKey:initial.id,version})});const body=await jsonOrError(response);const history=body.versions as VersionDto[];setVersions(history);setContent(history.find(v=>v.current)?.content??content);setDirty(false);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Restore failed");}finally{setBusy(null);}}
 async function ask(){if(!prompt.trim())return;setBusy("ai");setError("");try{const response=await fetch("/api/ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectKey:project.id,prompt,artifactId:initial.id})});const body=await jsonOrError(response);setAnswer(String(body.text??"No answer generated."));}catch(cause){setError(cause instanceof Error?cause.message:"AI request failed");}finally{setBusy(null);}}
 return <div className="workspace"><aside className="sidebar"><div className="sidebar-title">Artifacts</div>{project.artifacts.map(a=><a key={a.id} className={`nav-link ${a.id===initial.id?"active":""}`} href={`/projects/${project.id}/blueprint?artifact=${a.id}`}><span className="mono" style={{fontSize:10}}>{a.id}</span>{a.title}</a>)}</aside><section className="main"><header className="doc-head"><div><div className="doc-title">{initial.title}</div><div className="doc-meta mono">{initial.id} · v{currentVersion} · {initial.status}</div></div><div style={{display:"flex",gap:6}}><button className="btn btn-quiet" title="Edit" onClick={()=>setMode("edit")}><Columns2 size={15}/></button><button className="btn btn-quiet" title="Preview" onClick={()=>setMode("preview")}><Eye size={15}/></button>{canEdit&&<button className="btn" onClick={save} disabled={busy!==null}><Save size={14}/>{busy==="save"?"Saving":"Save version"}</button>}</div></header>{error&&<p role="alert" style={{color:"var(--danger)",padding:"0 24px"}}>{error}</p>}<div className="editor" style={mode==="split"?{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24,maxWidth:1200}:{}}>{mode!=="preview"&&<textarea aria-label="Markdown editor" value={content} readOnly={!canEdit} onChange={e=>{setContent(e.target.value);setDirty(true);}}/>} {mode!=="edit"&&<article className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown></article>}</div></section><aside className="intelligence"><div className="panel-title"><span>AI Intelligence</span><Bot size={15}/></div><div className="panel-block"><h3>Impact · {impact.severity}</h3><p>{impact.affected.length} connected artifacts may be affected.</p><a className="btn" href={`/projects/${project.id}/impact?source=${initial.id}`}>Review path</a></div><div className="panel-block"><h3>Spec health · {health.overall}</h3><p>{health.issues.length} findings. Traceability {health.traceability}%.</p></div><div className="panel-block"><h3><History size={13}/> Persisted history</h3>{versions.map(v=><div key={v.id} style={{display:"flex",alignItems:"center"}}><button className="btn btn-quiet" style={{flex:1,justifyContent:"space-between"}} onClick={()=>setContent(v.content)}>v{v.version}{v.current?" · current":""}</button>{canEdit&&!v.current&&<button className="btn btn-quiet" title={`Restore v${v.version} as a new version`} disabled={busy!==null} onClick={()=>restore(v.version)}><Undo2 size={13}/></button>}</div>)}</div><div className="panel-block"><h3>Ask with context</h3><textarea className="assistant-input" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="What breaks if this changes?"/><button className="btn btn-primary" style={{marginTop:8,width:"100%"}} onClick={ask} disabled={busy!==null}>{busy==="ai"?"Analyzing...":"Ask Nexora"}</button>{answer&&<p aria-live="polite" style={{color:"var(--ink)"}}>{answer}</p>}</div></aside></div>;
}
