import { hash } from "bcryptjs";import { ProjectRole } from "@prisma/client";import { db } from "../src/lib/db";import { createSession,revokeSession,verifySession } from "../src/lib/auth";import { getDiscoveryState,saveDiscoveryAnswer } from "../src/lib/discovery-repository";import { getOrCreateImpactProposal,reviewAllImpactItems } from "../src/lib/impact-repository";import { createRelationship,deleteRelationship,getProjectKnowledge,incrementRateLimit,listArtifactVersions,requireMembership,restoreArtifact,saveArtifact,createProjectWithOwner,addMember,setMemberRole,removeMember,listMembers } from "../src/lib/project-repository";import { getDesignContext,importDesignContext,parseDesignContextInput } from "../src/lib/design-context";import { createAiJob,processNextJob,getAiJob } from "../src/lib/ai-job";import { seed } from "../prisma/seed";

function check(value:unknown,message:string):asserts value{if(!value)throw new Error(message);}
async function main(){await seed();const owner=await db.user.findUniqueOrThrow({where:{email:"architect@nexora.local"}}),context=await requireMembership(owner.id,"nexora-demo",[ProjectRole.OWNER]);check(context,"owner membership missing");const artifact=await db.artifact.findUniqueOrThrow({where:{projectId_key:{projectId:context.projectId,key:"REQ-002"}}}),before=artifact.currentVersionNumber,original=(await listArtifactVersions(context.projectId,"REQ-002")).find(v=>v.current)!;
  const saved=await saveArtifact(context,{artifactKey:"REQ-002",content:`${original.content}\n\nIntegration persisted edit.`,reason:"integration",expectedVersion:before});check(saved.version===before+1,"save did not create next version");check((await getProjectKnowledge("nexora-demo"))?.artifacts.find(a=>a.id==="REQ-002")?.content.includes("Integration persisted edit"),"knowledge did not observe save");
  const restored=await restoreArtifact(context,{artifactKey:"REQ-002",version:original.version});check(restored.version===saved.version+1,"restore did not create a new version");check((await listArtifactVersions(context.projectId,"REQ-002")).length>=3,"history did not persist");
  const viewer=await db.user.upsert({where:{email:"viewer@nexora.local"},create:{email:"viewer@nexora.local",passwordHash:await hash("viewer-password",10)},update:{}});await db.projectMember.upsert({where:{projectId_userId:{projectId:context.projectId,userId:viewer.id}},create:{projectId:context.projectId,userId:viewer.id,role:"VIEWER"},update:{role:"VIEWER"}});check(await requireMembership(viewer.id,"nexora-demo",[ProjectRole.OWNER,ProjectRole.EDITOR])===null,"viewer received mutation access");
  const relation=await createRelationship(context,{sourceKey:"REQ-003",targetKey:"TEST-001",type:"VALIDATES",reason:"Integration relationship lifecycle"});check((await getProjectKnowledge("nexora-demo"))?.relationships.some(edge=>edge.id===relation.id),"relationship not visible in project knowledge");await deleteRelationship(context,relation.id);check(!(await getProjectKnowledge("nexora-demo"))?.relationships.some(edge=>edge.id===relation.id),"relationship delete failed");
  const proposal=await getOrCreateImpactProposal(context,"REQ-003");check(proposal.items.length>0,"impact proposal has no items");await reviewAllImpactItems(context,{proposalId:proposal.id,decision:"REJECTED"});check((await db.impactAnalysis.findUniqueOrThrow({where:{id:proposal.id}})).status==="REJECTED","proposal rejection not persisted");
  await saveDiscoveryAnswer(context,{category:"auth",skip:true});let discovery=await getDiscoveryState(context.projectId);check(discovery.skipped.includes("auth")&&discovery.missing.includes("auth")&&!discovery.sufficient,"skip incorrectly increased confidence");await saveDiscoveryAnswer(context,{category:"auth",value:"Owner, editor, and viewer permissions"});discovery=await getDiscoveryState(context.projectId);check(discovery.answered.includes("auth"),"answer not persisted");
  const session=await createSession(owner.id);check((await verifySession(session.token))?.userId===owner.id,"session not persisted");await revokeSession(session.token);check(await verifySession(session.token)===null,"logout did not revoke session");
  for(let i=0;i<3;i++)await incrementRateLimit({subject:"integration-user",action:"test",projectId:context.projectId,limit:2,windowSeconds:60});const limiter=await incrementRateLimit({subject:"integration-user",action:"test",projectId:context.projectId,limit:2,windowSeconds:60});check(!limiter.allowed,"database rate limit did not enforce limit");
const designBefore=await db.artifact.findFirst({where:{projectId:context.projectId,type:"DESIGN_CONTEXT",archivedAt:null}});
  const vinyasaPayload={schemaVersion:"1.0.0",metadata:{tool:"vinyasa",version:"0.3.0"},source:{url:"https://shop.example/",title:"Shop"},tokens:{colors:{primary:[{name:"brand",hex:"#2563eb",usage:55}],neutral:[{name:"ink",hex:"#111827",usage:40}]},typography:{families:[{raw:'"Inter", sans-serif'}],sizes:[{raw:"16px",px:16}]},spacing:[{raw:"8px",px:8}],radius:[{raw:"8px",px:8}]},health:{overall:91},accessibility:{wcagAA:{critical:1,warning:2,pass:8}},components:[{id:"button"}]};
  const firstImport=await importDesignContext(context,{ctx:parseDesignContextInput(vinyasaPayload).ctx});check(firstImport.artifactKey==="DESIGN-001"&&firstImport.version===(designBefore?designBefore.currentVersionNumber+1:1),"design import did not create next version");const knowledge=await getProjectKnowledge("nexora-demo");const designArtifact=knowledge?.artifacts.find(a=>a.type==="design-context");check(designArtifact?.content.includes("#2563eb"),"design artifact content missing tokens");const derived=knowledge?.relationships.some(edge=>edge.sourceId==="DESIGN-001"&&edge.targetId==="PRD-001"&&edge.type==="derived_from");check(derived,"design context not derived from PRD");const designRow=await getDesignContext(context.projectId);check(designRow?.ctx?.health.overall===91&&designRow?.checksum,"design context row missing");
  const secondImport=await importDesignContext(context,{ctx:parseDesignContextInput({...vinyasaPayload,health:{overall:95}}).ctx});check(secondImport.version===firstImport.version+1,"repeat design import did not create next version");check((await getDesignContext(context.projectId))?.artifactVersion===secondImport.version,"design context row did not track update");
const fresh=await db.user.upsert({where:{email:"fresh@nexora.local"},create:{email:"fresh@nexora.local",passwordHash:await hash("fresh-password",10)},update:{}});const created=await createProjectWithOwner(fresh.id,{name:"Fresh Project",description:"identity phase"});check(created.key&&(await requireMembership(fresh.id,created.key,[ProjectRole.OWNER])),"owner membership missing at creation");const freshId=created.id;check((await getProjectKnowledge(created.key))?.artifacts.some(a=>a.id==="PRD-001"&&a.type==="prd"),"project seed PRD missing");
  await addMember(freshId,owner.email,"EDITOR");const members=await listMembers(freshId);check(members.some(m=>m.user.email===owner.email&&m.role==="EDITOR"),"member not added");const ownerMembership=members.find(m=>m.user.email===owner.email)!;await setMemberRole(fresh.id,freshId,ownerMembership.id,"VIEWER");check((await listMembers(freshId)).find(m=>m.id===ownerMembership.id)?.role==="VIEWER","role change failed");let downgradeBlocked=false;try{await setMemberRole(fresh.id,freshId,members.find(m=>m.user.email===fresh.email)!.id,"VIEWER");}catch{downgradeBlocked=true;}check(downgradeBlocked,"last owner downgrade was not blocked");await removeMember(fresh.id,freshId,ownerMembership.id);check(!(await listMembers(freshId)).some(m=>m.id===ownerMembership.id),"member removal failed");
const queued=await createAiJob({projectId:context.projectId,userId:owner.id,prompt:"Summarize the workspace isolation requirement",artifactId:"REQ-001"});check(queued.status==="PENDING","ai job not queued");check(await processNextJob(),"ai job not claimed");const completedJob=await getAiJob(context.projectId,queued.id);check(completedJob?.status==="COMPLETED"&&completedJob.result,"ai job did not complete durably");
  console.log("Integration assertions passed: persistence, versions, restore, roles, impact, discovery, sessions, rate limits, design bridge, identity, ai-queue");}
main().finally(()=>db.$disconnect()).catch(error=>{console.error(error);process.exit(1);});
