import { db } from "../src/lib/db";

const base=process.env.E2E_BASE_URL??"http://127.0.0.1:3421",origin={origin:base,"content-type":"application/json"};
function check(value:unknown,message:string):asserts value{if(!value)throw new Error(message);}
async function login(email:string,password:string){const response=await fetch(`${base}/api/auth/login`,{method:"POST",headers:origin,body:JSON.stringify({email,password})});check(response.status===200,`login failed: ${response.status}`);return response.headers.get("set-cookie")!.split(";")[0];}
async function json(response:Response){const text=await response.text();return text?JSON.parse(text):{};}
async function main(){
  const ownerCookie=await login("architect@nexora.local","nexora-production-foundation"),ownerHeaders={...origin,cookie:ownerCookie};
  const initial=await json(await fetch(`${base}/api/artifacts?project=nexora-demo&artifact=REQ-001`,{headers:ownerHeaders})),current=initial.versions.find((version:{current:boolean})=>version.current),marker=`E2E persisted ${Date.now()}`;
  const save=await fetch(`${base}/api/artifacts`,{method:"PATCH",headers:ownerHeaders,body:JSON.stringify({projectKey:"nexora-demo",artifactKey:"REQ-001",content:`${current.content}\n\n${marker}`,reason:"E2E save",expectedVersion:current.version})});check(save.status===200,`save failed: ${save.status}`);const saved=await json(save),savedVersion=saved.artifact.version;
  const reload=await json(await fetch(`${base}/api/artifacts?project=nexora-demo&artifact=REQ-001`,{headers:ownerHeaders}));check(reload.project.artifacts.find((a:{id:string})=>a.id==="REQ-001").content.includes(marker),"reload did not observe saved content");
  const restore=await fetch(`${base}/api/artifacts/restore`,{method:"POST",headers:ownerHeaders,body:JSON.stringify({projectKey:"nexora-demo",artifactKey:"REQ-001",version:current.version})});check(restore.status===200,"restore failed");const restored=await json(restore);check(restored.artifact.version===savedVersion+1,"restore did not create next version");
  const viewer=await db.user.findUniqueOrThrow({where:{email:"viewer@nexora.local"}});await db.user.update({where:{id:viewer.id},data:{passwordHash:(await import("bcryptjs")).hashSync("viewer-password",10)}});const viewerCookie=await login("viewer@nexora.local","viewer-password"),viewerHeaders={...origin,cookie:viewerCookie};const denied=await fetch(`${base}/api/artifacts`,{method:"PATCH",headers:viewerHeaders,body:JSON.stringify({projectKey:"nexora-demo",artifactKey:"REQ-001",content:"forbidden viewer mutation"})});check(denied.status===403,`viewer mutation returned ${denied.status}`);
  const impact=await json(await fetch(`${base}/api/impact?project=nexora-demo&source=REQ-002`,{headers:ownerHeaders}));check(impact.id&&impact.items.length,"impact proposal missing");const impactedKey=impact.items[0].artifact.key,beforeImpact=(await json(await fetch(`${base}/api/artifacts?project=nexora-demo&artifact=${impactedKey}`,{headers:ownerHeaders}))).project.artifacts.find((item:{id:string})=>item.id===impactedKey).content;const apply=await fetch(`${base}/api/impact`,{method:"POST",headers:ownerHeaders,body:JSON.stringify({projectKey:"nexora-demo",proposalId:impact.id,decision:"ACCEPTED"})});check(apply.status===200,`impact apply failed: ${apply.status}`);check((await db.impactAnalysis.findUniqueOrThrow({where:{id:impact.id}})).status==="APPLIED","impact status not persisted");const afterImpact=(await json(await fetch(`${base}/api/artifacts?project=nexora-demo&artifact=${impactedKey}`,{headers:ownerHeaders}))).project.artifacts.find((item:{id:string})=>item.id===impactedKey).content;check(afterImpact!==beforeImpact&&afterImpact.includes("Impact synchronization"),"accepted impact did not mutate artifact content");
  const discovery=await fetch(`${base}/api/discovery`,{method:"POST",headers:ownerHeaders,body:JSON.stringify({projectKey:"nexora-demo",category:"scale",skip:true})});const discoveryBody=await json(discovery);check(discovery.status===200&&discoveryBody.skipped.includes("scale")&&discoveryBody.missing.includes("scale"),"discovery skip semantics failed");
  const exported=await fetch(`${base}/api/export?project=nexora-demo&target=opencode`,{headers:ownerHeaders});const zip=await exported.arrayBuffer();check(exported.status===200&&exported.headers.get("content-type")==="application/zip"&&zip.byteLength>500,"ZIP export failed");
  const designPayload={schema:"nexora.design-context",version:1,generatedBy:"vinyasa 0.3.0",sourceUrl:"https://shop.example/",sourceTitle:"Shop",generatedAt:new Date().toISOString(),designSystem:{colors:[{name:"brand",hex:"#2563eb",usage:55}],neutralColors:[],fontFamilies:["Inter"],fontSizes:[{value:"16px",px:16}],spacing:[] ,radius:[]},health:{overall:91},accessibility:{critical:1,warning:2,pass:8},components:{total:1}};const designImport=await fetch(`${base}/api/design-context`,{method:"POST",headers:ownerHeaders,body:JSON.stringify({projectKey:"nexora-demo",payload:designPayload})});check(designImport.status===201,`design context import failed: ${designImport.status}`);const designContext=await json(await fetch(`${base}/api/design-context?project=nexora-demo`,{headers:ownerHeaders}));check(designContext.design?.ctx?.designSystem.colors.length>=1,"design context readback failed");const mcpDesign=await json(await fetch(`${base}/api/mcp`,{method:"POST",headers:ownerHeaders,body:JSON.stringify({projectKey:"nexora-demo",tool:"get_design_context",arguments:{}})}));check(mcpDesign.content?.ctx,"MCP design context missing");
  const logout=await fetch(`${base}/api/auth/logout`,{method:"POST",headers:ownerHeaders});check(logout.status===200,"logout failed");const owner=await db.user.findUniqueOrThrow({where:{email:"architect@nexora.local"},include:{sessions:{orderBy:{createdAt:"desc"},take:1}}});check(owner.sessions[0]?.revokedAt,"session row was not revoked");const revoked=await fetch(`${base}/api/artifacts?project=nexora-demo`,{headers:ownerHeaders});check(revoked.status===404,`revoked session returned ${revoked.status}: ${await revoked.text()}`);
  console.log("E2E assertions passed: login, save/reload, restore, viewer denial, impact apply, discovery, ZIP export, design bridge, logout revocation");
}
main().finally(()=>db.$disconnect()).catch(error=>{console.error(error);process.exit(1);});
